baseURL = 'https://juliusbroomfield.github.io/'
languageCode = 'en-us'
title = 'Julius Broomfield'
theme = 'barks'
favicon = 'static/favicon.ico'

[params.head]
    author = "Julius Broomfield"
    description = "Hi, I'm Julius, and this is my website!"

[params.colors]
    theme_color = "#333333"
    background_color = "#fcfbf9"
    text_color = "#333333"
    link_color = "#9277B0"

[menus]

[[menu.main]]
    name = "Papers"
    url = "https://juliusbroomfield.github.io/docs/Official_Resume.pdf"
    weight = 1
[[menu.main]]
    name = "Reading"
    url = "https://juliusbroomfield.github.io/docs/Official_Resume.pdf"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "https://juliusbroomfield.github.io/docs/Official_Resume.pdf"
    weight = 1

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:broomfieldjuliusr@gmail.com"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/juliusbroomfield"
        weight = 2
    [params.social.linkedin]
        name = "LinkedIn"
        class = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/in/juliusbroomfield/"
        weight = 3
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=mXzRbw8AAAAJ&hl=en&authuser=1"
        weight = 4
        
